language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: Xh/ptVRBp4klo7XQIR5HduFqU2QsbYpw/JC/JfSq/E4bH8X72Y1h67wxRHTXioRiShkwwzmm+bUF+hBicz8ZGI9PByagVnIpaqabNSdzO744tYlnJI0bbsIdD4kMduTfQS8LKNAR3/h76m5a5/vfLLqRPMLOJVkc9C80PYLFA3E=
  - secure: Qw+31jyJz3V01JVS/gxQHS0v16+G9YLuckThiFoQ6LxSvdBv2wLEhfzefz3WjgvkzKKaot696+vYVxkkK3J8TyAX0Tk8rDWMf2KVtEb91WTS4zP1pBH9Fcl0mnzl74aMmveKfH3G+sHdbRniZq4YwAAbyS/8m4oGMQgQbOjngJs=
